### PR TITLE
added a database reconnection functionality

### PR DESCRIPTION
**Pull request by fberber**

### CODE REVIEW

**Comment by fberber** [comment]
When the connection to the database is lost, the connection is not established even though the 'autoconnect' parameter is enabled.

Now, before each access to the database, the connection is checked and re-established if necessary!

**Comment by cookie33** [comment]
Hi,

Will this also update the ePIC version to 2.5.2? Was this observed after a mysql upgrade and the connection was lost?

We had the following problem after a mysql upgrade:

```
[24/Mar/2016:11:18:38 +0100]  PUT from 841@127.0.0.1 on /handles/841/NagiosTesthandle  >> APPLICATION STOPPED: Cannot connect to database!.
```

We never saw this before. Has this also to do with the fact that the reload parameter is set to off?

greetings,

Robert

**Comment by fberber** [comment]
Hi Robert,

> APPLICATION STOPPED: Cannot connect to database!
> This is exactly what happens! 
> The version with the multihosting capability was pushed into a new branch. So, yes this is then version 2.5.2, which have to be documented :)

Kind Regards
Fatih

## 

Fatih Berber           E-Mail: fatih.berber@gwdg.de mailto:fatih.berber@gwdg.de
                               Tel:    +49 551 39 20362

---

GWDG - Gesellschaft für wissenschaftliche
Datenverarbeitung mbH Göttingen
Am Faßberg 11, 37077 Göttingen

Fon: 0551 201-1510
Fax: 0551 201-2150
E-Mail: support@gwdg.de mailto:support@gwdg.de

## WWW: www.gwdg.de http://www.gwdg.de/

Geschäftsführer: Prof. Dr. Ramin Yahyapour
Aufsichtsratsvorsitzender: Prof. Dr. Christian Griesinger
Sitz der Gesellschaft: Göttingen
Registergericht: Göttingen

## Handelsregister-Nr. B 598

## Zertifiziert nach ISO 9001

**Comment by cookie33** [comment]
installed on a test instance and tested:

```
09:01 fqdn:/home/handle1/epic_v2_tests
handle1$ ./test.sh
test1.1.sh: Directory listing: XHTML: OK
test1.2.sh: Directory listing: JSON: OK
test2.2.sh: Handle URL: PUT and GET application/json: OK
test3.0.sh: Handle URL: DELETE: OK
test4.0.sh: Handle URL: PUT a new handle with different modes: OK
test5.0.sh: Handle URL: POST a new templated handle: OK
All tests completed successfully.
```

So for normal work it seems to function..

**Comment by tkalman** [comment]
Closing this pull request and creating an up-to-date without conflicts and with the correct version numbers.

**Pull request closed without merging**
